kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8083
    protocol: TCP  # Changed from 80 to avoid potential conflicts
  - containerPort: 443
    hostPort: 8443
    protocol: TCP  # Changed from 443 to avoid potential conflicts
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP  # For Jenkins UI (changed from 8080 to avoid port conflict)
- role: worker
- role: worker

# Simplified networking configuration
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
