apiVersion: v2
name: myapp
description: A Helm chart for the Flask application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Platform Team
    email: platform@example.com
keywords:
  - flask
  - python
  - web
home: https://github.com/example/k8s-platform-monorepo
sources:
  - https://github.com/example/k8s-platform-monorepo/tree/main/apps/flask
