# Default values for the Flask application Helm chart
# This is a YAML-formatted file.

# Replica count
replicaCount: 2

# Image configuration
image:
  repository: ghcr.io/example/flask-app
  tag: latest
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 5001

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    spec.ingressClassName: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: flask-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Liveness probe
livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

# Readiness probe
readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

# Environment variables
env:
  - name: ENVIRONMENT
    value: "production"
  - name: DEBUG
    value: "False"
  - name: APP_VERSION
    value: "1.0.0"

# ConfigMap for additional configuration
configMap:
  enabled: false
  data: {}

# Secret for sensitive data
secret:
  enabled: false
  data: {}

# Persistence configuration
persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: "standard"
