apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-secrets-access
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-secrets-access
  namespace: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-secrets-access
  apiGroup: rbac.authorization.k8s.io
